spring.application.name=BirthdayApp
server.port=${PORT:8080}

# Security Configuration
# Usuario admin con password: Admin2024!
spring.security.user.name=admin
spring.security.user.password=Admin2024!

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://birthdayapp_user:EffetaEffeta.admin2026@effeta.bg7eptg.mongodb.net/birthdayapp?retryWrites=true&w=majority&appName=Effeta}
spring.data.mongodb.database=${MONGODB_DATABASE:birthdayapp}
